language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install -r optional-requirements.txt
  - pip install Django==${DJANGO}

script:  python manage.py test --settings=explorer.tests.settings
env:
  - DJANGO=1.7.7
  - DJANGO=1.8.5
  - DJANGO=1.9.1
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7.7
    - python: 2.6
      env: DJANGO=1.8.5
