language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install -r optional-requirements.txt
  - pip install Django==${DJANGO}

script:  python manage.py test
env:
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
matrix:
  exclude:
    - python: 3.5
      env: DJANGO="Django>=1.7,<1.8"
