language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install ${DJANGO}
  - pip install -r requirements.txt
  - pip install -r optional-requirements.txt

script:  python manage.py test
env:
  - DJANGO="Django==1.11.*"
  - DJANGO="Django==2.0.*"
  - DJANGO="Django==2.1.*"
  - DJANGO="Django==2.2.*"
  - DJANGO="Django==3.0.*"
